---
title: "Demand Planning"
author: "Ken Brooks"
date: "November 4, 2015"
output: pdf_document
---

Analysis of reprint report

```{r libraries}
# clear environment and load libraries
rm(list = ls())

#install.packages("readxl")
#install.packages("forecast")
library(xts)
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
library(lubridate)
library(forecast)
```

Read file

```{r read, echo=FALSE}
setwd("~/Documents/Macmillan/Projects/Demand Planning")

filename <- file.choose()

# data = read_csv(filename, sheet = 1, skip = 0)

data = read.csv(filename)
```

```{r select}

names(data)

valid_column_names <- make.names(names=names(data), unique=TRUE, allow_ = TRUE)

names(data) <- valid_column_names
names(data)

data = rename(data, Demand.Units = Gross.Units.....Comp.Units)

saveRDS(data, "data.rds")

```


```{r demand.ts}

# Build a ts object for further analysis

data = readRDS("data.rds")

glimpse(data)

# Eliminate all columns but Title, Month and Demand.Units
demand = dplyr::select(data, 
  Title, 
  Month,
  Demand.Units)

glimpse(demand)

# Change format of Month into a date

demand$Month = parse_date_time(as.character(demand$Month), "%Y%m")
glimpse(demand)

# Filter by Title to make things simple.  Note for later forecasting models to work, the title can't have 0 or negative values (I think).

# demand2 = filter(demand, Title == "DEAD CSCC")
demand2 = filter(demand, Title == "AMERICAN LIT: SCARLET LETTER")

# Build a ts object (time series)

data.ts = ts(demand2$Demand.Units, start = c(2011, 11), frequency = 12)

plot(data.ts)

```

```{r forecast}

plot(data.ts)
seasonplot(data.ts, 12, year.labels = FALSE)
tsdisplay(data.ts)

lag.plot(data.ts, lags=12)
spectrum(data.ts)

plot(forecast(data.ts))

# ets smoothing
fit <- ets(data.ts)
fit2 <- ets(data.ts,model="ZZZ",damped=FALSE)
fcast1 <- forecast(fit, h=24)
fcast2 <- forecast(fit2, h=24)
plot(fcast1)
plot(fcast2)

```

```{r details}
str(fcast1)  # uncomment to see all of the data available

fcast1$method # Model used
fcast1$model$par # parameters
fcast1$mean # forecasted values


```


```{r HoltWinters}
# I think HoltWinters method is already done automatically above, so this chunk is redundant

plot(data.ts)

fit.hw <- HoltWinters(data.ts, seasonal = "mult")

fcast3 <- forecast(fit.hw, h=24)
plot(fcast3)

```


Next steps:
-----------
* Extract seasonality factors
* Calculate OP/OQ
* Output in useful format (Excel?)
* Sequential forecasting
  * Enough data
  * Not enough for seasonality (use group coefficients)
  * Not enough for any forecast (use similar title)


Experiment in clustering time series - not working!
---------------------------------------------------

```{r tsclust}
# this is to cluster by seasonality pattern once we figure out how to do it.  The following is only an example.

library(TSclust)

# Get all of the time series
data(interest.rates)
rownames(interest.rates)
colnames(interest.rates)
str(interest.rates)
# note that this is a matrix with timeseries in columns. To get this from our data we will need to spread the titles across the columns
data = readRDS("data.rds")
demand = dplyr::select(data, Title, Demand.Units)

df.plot <- spread(df.Follett.biz, type, value = value)

demand2 = tidyr::spread(demand, Title, value = Demand.Units)
valid_column_names <- make.names(names=names(demand2), unique=TRUE, allow_ = TRUE)

names(demand2) <- valid_column_names
names(demand2)
rownames(demand2) <- demand2$Month

demand3 = demand2[,-1]  # this is a dataframe and supposedly TSClust uses them too

###transformation of the interest rates
trans.inter.rates <- log(interest.rates[2:215,]) - log(interest.rates[1:214,])

##use the dist function of the proxy package to easily create the dist object
#applying ACF with geometric decaying to each pair of time series
tsdist <- diss( t(trans.inter.rates) , "ACF", p=0.05)  # note the transpose

tsdist2 <- TSclust::diss( t(demand3), "EUCL", p=0.05)  # PROBLEMS HERE - Elimin NA

names(tsdist) <- colnames(interest.rates)

#perform hierachical clustering to the dist object
hc <- hclust(tsdist)

#show the results
plot(hc)

mahdist <- diss( t(trans.inter.rates) , "AR.MAH", p=0.05)$p_value

pvalues.clust(mahdist, 0.05)

```



