---
title: "Recommended Print List"
author: "Ken Brooks"
date: "November 13, 2015"
output: pdf_document
---

Prepare Environment
-------------------

```{r libraries, warning=FALSE, echo=FALSE, error=FALSE}
# clear environment and load libraries
rm(list = ls())

library(xts)
library(readxl)
library(plyr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(lubridate)
library(forecast)

```

Import data
-----------

```{r read, echo=FALSE}
setwd("~/Documents/Macmillan/Projects/Demand Planning")

#filename <- file.choose()

filename <- "Sales by month.csv"
#filename <- "Sales by month v2.csv"

# data = read_csv(filename, sheet = 1, skip = 0)

data = read.csv(filename)
```

```{r select}

names(data)


valid_column_names <- make.names(names=names(data), unique=TRUE, allow_ = TRUE)
names(data) <- valid_column_names

data$Title <- gsub("..", ".", make.names(data$Title, allow_ = TRUE), fixed = TRUE)
data$Author <- gsub("..", ".", make.names(data$Author, allow = TRUE), fixed = TRUE)
data$Ean <- as.factor(as.character(data$Ean))
#data$Ean <- as.factor(as.character(data$Prev.Ean))
data$Pub.Date <- as.Date(data$Pub.Date)

data = dplyr::rename(data, Demand.Units = Gross.Units.....Comp.Units)

saveRDS(data, "data.rds")

```

Build title table
-----------------

```{r title.table}

# Retrieve stored data
data = readRDS("data.rds")


title.data = data %>% dplyr::select(Author, Isbn, Ean, Title, Pub.Date, Medium, Ans.Code, Available,
                                    Consignment.On.Hand, Reserved.Stock, Sets.Made.Up) %>%
  distinct(Author, Isbn, Ean, Title, Pub.Date, Medium, Ans.Code, Available,
                                    Consignment.On.Hand, Reserved.Stock, Sets.Made.Up)

saveRDS(title.data, "title_data.rds")

```

Build time series objects
-------------------------

```{r time.series, warning=FALSE, error=FALSE}
# The purpose of this chunk is to create time series objects for a large number of titles

# Retrieve stored data
data = readRDS("data.rds")

demand = data %>% dplyr::select(Month, Isbn, Demand.Units) %>%
  tidyr::spread(key = Isbn, value = Demand.Units)
rownames(demand) <- demand$Month
demand3 = demand[,-1] # Remove the Month column since it's now rownames

demand4 = ts(demand3, start = c(2012, 11), frequency = 12)

saveRDS(demand4, "time_series.rds")

```


Forecast time series
--------------------

```{r forecast, warning=FALSE, error=FALSE}
# The purpose of this chunk is to generate forecasts for many titles at once

# Get all of the time series and title data
time.series = readRDS("time_series.rds")
title.data = readRDS("title_data.rds")

# create a function to forecast a series based on a ts and df index

n.mo.fcst2 <- function(isbn){
  ts1 = time.series[, isbn]
  # if there's more than 24 months of data, generate forecast,
  # else generate a zero forecast to drive a manual review.
  # This needs to generate the forecast to see if it's flat.
  # If it's flat, replace it with a zero forecast to drive
  # a manual review.
  if(sum(!is.na(ts1)) < 25){  
    ts1.temp = ts(rep(0,length(ts1)), start = start(ts1), frequency = frequency(ts1))
    ts1.fcst = forecast(ts1.temp, h=15)$mean
    }
  else{
    ts1.fcst = forecast(ts1, h=15)$mean}
  ts1.fcst
}

# use ldply to apply it to a list of ISBNs

title.forecasts <- ldply(title.data$Isbn, n.mo.fcst2)
# add names
title.data$Isbn
rownames(title.forecasts) <- as.character(title.data$Isbn)

rownames(title.forecasts[1,])

# Note that titles are in rows!

title.forecasts <- title.forecasts %>% mutate(three = rowSums(.[1:3])) %>%
  mutate(six = rowSums(.[1:6])) %>%
  mutate(nine = rowSums(.[1:9])) %>%
  mutate(twelve = rowSums(.[1:12])) %>%
  mutate(fifteen = rowSums(.[1:15]))

saveRDS(title.forecasts, "forecasts.rds")
write.csv(file="Title_forecasts.csv", x=title.forecasts)

```

Review Individual Titles
------------------------

```{r}

time.series = readRDS("time_series.rds")
title.data = readRDS("title_data.rds")

title.data$Isbn

isbn1 <- "0312132921"
isbn2 <- "031241501X" # skewed title 1
isbn3 <- "312566735" # skewed title 2
isbn4 <- "145760647X" # skewed title 3

skewed.isbns <- as.list(c(isbn2, isbn3, isbn4))
ts1 = time.series[, isbn4]
sum(!is.na(ts1))
ts1.fcst = forecast(ts1, h = 15)
plot(ts1.fcst)

```

Plot two time series on a single axis

```{r plot.two}
# Get series 1
isbn1 <- "0312132921"
isbn2 <- "031241501X"

plot.two <- function(isbn1, isbn2, ts) {
  combined.isbns <- c(isbn1, isbn2)
  combined <- subset(ts, select =  combined.isbns)
  ts.plot(combined,gpars= list(col=rainbow(10)))
}

plot.two(isbn1, isbn2, time.series)

```


Recommend titles to examine
---------------------------

```{r}

title.data = readRDS("title_data.rds")
title.forecasts = readRDS("title.forecasts.rds")

# add another column for whether a review is required

calc.review <- function(forecast, onhand){
  if(forecast == 0){"Insuff data"}
  else if(forecast > onhand){"Print review"}
  else{"No Review"}
}

title.planning <- title.data %>% rowwise() %>% 
  dplyr::mutate(Review = calc.review(title.forecasts$three, (Available + Reserved.Stock + Sets.Made.Up))) %>% 
  dplyr::arrange(Review) %>% 
  mutate(OQ.6 = title.forecasts$six) %>% 
  mutate(OQ.9 = title.forecasts$nine) %>% 
  mutate(OQ.12 = title.forecasts$twelve) %>% 
  mutate(OQ.15 = title.forecasts$fifteen)

# output to csv

saveRDS(title.planning, "title_planning.rds")
write.csv(file="Title_Planning.csv", x=title.planning)

```
