---
title: "Recommended Print List"
author: "Ken Brooks"
date: "November 13, 2015"
output: pdf_document
---

To Do
-----
1. Fix the forecast function to look for a non-seasonal model and recommend a manual review
2. Fix the forecast model to only forecast when there's enough data - research what this limit is.
3. Create function to look up previous edition and run it through the plot.two function. 
  a. Fail gracefully.  Should it only plot one? Should it print a message that there's no previous edition?
  b. Determine what kind of timing shift should be done, if any.
4. Trim plot.two function of leading white space

Prepare Environment
-------------------

```{r libraries, warning=FALSE, echo=FALSE, error=FALSE}
# clear environment and load libraries
rm(list = ls())

library(xts)
library(readxl)
library(plyr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(lubridate)
library(forecast)

```

Import data
-----------

```{r read, echo=FALSE}
setwd("~/Documents/Macmillan/Projects/Demand Planning")

#filename <- file.choose()

#filename <- "Sales by month.csv"
filename <- "Sales by month v3.csv"

# data = read_csv(filename, sheet = 1, skip = 0)
data = read.csv(filename)
```

Check that nothing has changed in the input data
------------------------------------------------

```{r checkdata}

str(data)
dim(data)[2] == 16
is.factor(data$Author)
is.factor(data$Isbn)
is.numeric(data$Ean)
is.factor(data$Title)
is.factor(data$Pub.Date)
is.factor(data$Medium)
is.factor(data$Ans.Code)
is.integer(data$Available)
is.integer(data$Consignment.On.Hand)
is.integer(data$Reserved.Stock)
is.integer(data$Sets.Made.Up)
is.integer(data$Month)
is.integer(data$Gross.Units)
is.integer(data$Return.Units)
is.factor(data$Prev.Edition.Isbn)
is.numeric(data$Prev.Edition.Ean)

```

Clean up imported data
----------------------

```{r format.data}

names(data)


valid_column_names <- make.names(names=names(data), unique=TRUE, allow_ = TRUE)
names(data) <- valid_column_names

data$Title <- gsub("..", ".", make.names(data$Title, allow_ = TRUE), fixed = TRUE)
data$Author <- gsub("..", ".", make.names(data$Author, allow = TRUE), fixed = TRUE)
data$Ean <- as.factor(as.character(data$Ean))
data$Prev.Edition.Ean <- as.factor(as.character(data$Prev.Edition.Ean))
data$Pub.Date <- as.Date(as.character(data$Pub.Date), format = "%m/%d/%Y")
# data$Month <- as.Date(as.character(data$Month), format = "%Y%m")

data$Month = as.Date(paste(as.character(data$Month), "01", sep = ""), format = "%Y%m%d")

# Eliminate duplicates, if any:
data <- unique(data)  # Note that this might cause problems later!

str(data)
summary(data)

saveRDS(data, "data.rds")

```

Build title table
-----------------

```{r title.table}

# Retrieve stored data
data = readRDS("data.rds")

names(data)

title.data = data %>% dplyr::select(Author, Isbn, Ean, Title, Pub.Date, Medium, Ans.Code, Available, Consignment.On.Hand, Reserved.Stock, Sets.Made.Up, Prev.Edition.Isbn, Prev.Edition.Ean) %>%
  distinct(Author, Isbn, Ean, Title, Pub.Date, Medium, Ans.Code, Available,
    Consignment.On.Hand, Reserved.Stock, Sets.Made.Up, Prev.Edition.Isbn, Prev.Edition.Ean)

saveRDS(title.data, "title_data.rds")

```

Build time series objects
-------------------------

```{r time.series, warning=FALSE, error=FALSE}
# The purpose of this chunk is to create time series objects for a large number of titles

# Retrieve stored data
data = readRDS("data.rds")

names(data)

demand = data %>% dplyr::select(Month, Isbn, Gross.Units) 

demand = tidyr::spread(demand, key = Isbn, value = Gross.Units)

# Get the earliest month in order to align dates

earliest.date = min(demand$Month)

rownames(demand) <- demand$Month
demand3 = demand[,-1] # Remove the Month column since it's now rownames

# Get the earliest month

demand4 = ts(demand3, start = c(year(earliest.date), month(earliest.date)), frequency = 12)

saveRDS(demand4, "time_series.rds")

```


Forecast time series
--------------------

```{r forecast, warning=FALSE, error=FALSE}
# The purpose of this chunk is to generate forecasts for many titles at once

# Get all of the time series and title data
time.series = readRDS("time_series.rds")
title.data = readRDS("title_data.rds")

# create a function to forecast a series based on a ts and df index

n.mo.fcst2 <- function(isbn){  # note that this should be a 2 param fn
  ts1 = time.series[, isbn]
  # if there's more than 24 months of data, generate forecast,
  # else generate a zero forecast to drive a manual review.
  # This needs to generate the forecast to see if it's flat.
  # If it's flat, replace it with a zero forecast to drive
  # a manual review.
  if(sum(!is.na(ts1)) < 25){  
    ts1.temp = ts(rep(0,length(ts1)), start = start(ts1), frequency = frequency(ts1))
    ts1.fcst = forecast(ts1.temp, h=15)$mean
    }
  else{
    ts1.fcst = forecast(ts1, h=15)$mean}
  ts1.fcst
}

# use ldply to apply it to a list of ISBNs

title.forecasts <- ldply(title.data$Isbn, n.mo.fcst2)
# add names
title.data$Isbn
rownames(title.forecasts) <- as.character(title.data$Isbn)

rownames(title.forecasts[1,])

# Add cumulative forecast quantities. Note that titles are in rows!

title.forecasts <- title.forecasts %>% mutate(three = rowSums(.[1:3])) %>%
  mutate(six = rowSums(.[1:6])) %>%
  mutate(nine = rowSums(.[1:9])) %>%
  mutate(twelve = rowSums(.[1:12])) %>%
  mutate(fifteen = rowSums(.[1:15]))

saveRDS(title.forecasts, "forecasts.rds")
write.csv(file="Title_forecasts.csv", x=title.forecasts)

```

Review Individual Titles
------------------------

```{r}

time.series = readRDS("time_series.rds")
title.data = readRDS("title_data.rds")

title.data$Isbn

isbn1 <- "0312132921"
isbn2 <- "031241501X" # skewed title 1
isbn3 <- "312566735" # skewed title 2
isbn4 <- "145760647X" # skewed title 3

skewed.isbns <- as.list(c(isbn2, isbn3, isbn4))
ts1 = time.series[, isbn4]
sum(!is.na(ts1))
ts1.fcst = forecast(ts1, h = 15)
plot(ts1.fcst)

```

Find previous ISBN
------------------

```{r prev.isbn}

title.data = readRDS("title_data.rds")

# head(title.data, 50)

isbn1 <- "1429231246"
isbn2 <- "0312132921"

previous.edition.isbn <- function(isbn, title.df){
  # Returns the previous edition ISBN.  Takes ISBN as a string, and a data frame
  # as an input and returns the previous ISBN as a string, or NA if no previous
  # ISBN is available.
  result <- as.character(title.df[title.df$Isbn == isbn, "Prev.Edition.Isbn"])
  if (result == "")
    {NA}
  else {result}
}


# Tests for previous.edition.isbn
previous.edition.isbn("1429231246", title.data) == "0716761211"
is.na(previous.edition.isbn("0312132921", title.data))

```

Plot two time series on a single axis

```{r plot.two}

isbn1 <- "031241501X"
isbn2 <- "031243829X"
time.series = readRDS("time_series.rds")

plot.two <- function(isbn1, isbn2, ts) {
  # Plots two ISBNs in a facet plot, one over the other.  Takes 2 ISBNs as
  # strings and a time series data frome as input and generates two plots.
  plot(ts[,c(isbn1, isbn2)], main = "Comparative Time Series Plot",
       at = "pretty")
}

plot.two(isbn1, isbn2, time.series)

```

Plot title and previous edition (if any)
----------------------------------------

```{r previous.edition}

time.series = readRDS("time_series.rds")
title.data = readRDS("title_data.rds")

isbn1 = "1319056911"  # How Life Works
isbn2 = "0312132921"
isbn3 <- "031243829X"

plot.previous.edition <- function(isbn, ts.data, title.data){
  # Takes an ISBN as a string and two data frames: title data and title
  # time series as inputs and plots a facet plot of the time series and
  # the previous edition.  If there is no previous edition, or there is 
  # no associated time series data, returns an NA
  
  isbn.prev <- previous.edition.isbn(isbn, title.data) # Get previous edition
  
  # Fail if there's no previous edition (isbn.prev == NA)
  if (is.na(isbn.prev)) {
    return(NA)
    }
  
  # Fail if previous edition has no data (not yet implemented)
  
  # Plot results
  plot.two(isbn1, isbn.prev, time.series)
}

# Test plot.previous.edition
plot.previous.edition(isbn1, time.series, title.data)
plot.previous.edition(isbn2, time.series, title.data)

isbn3 <- "031243829X"
plot.previous.edition(isbn3, time.series, title.data)

```

Recommend titles to examine
---------------------------

```{r}

title.data = readRDS("title_data.rds")
title.forecasts = readRDS("forecasts.rds")

# add another column for whether a review is required

calc.review <- function(forecast, onhand){
  if(forecast == 0){"Insuff data"}
  else if(forecast > onhand){"Print review"}
  else{"No Review"}
}

title.planning <- title.data %>% rowwise() %>% 
  dplyr::mutate(Review = calc.review(title.forecasts$three, (Available + Reserved.Stock + Sets.Made.Up))) %>% 
  dplyr::arrange(Review) %>% 
  mutate(OQ.6 = title.forecasts$six) %>% 
  mutate(OQ.9 = title.forecasts$nine) %>% 
  mutate(OQ.12 = title.forecasts$twelve) %>% 
  mutate(OQ.15 = title.forecasts$fifteen)

# output to csv

saveRDS(title.planning, "title_planning.rds")
write.csv(file="Title_Planning.csv", x=title.planning)

```
